pipeline {
    agent {
        label "jenkins_172.30.14.126"
    }

    stages {
        stage('代码检出') {
            steps {
                checkout scm   // 必须保留，否则Git元数据无法获取
            }
        }

        stage('强制失败测试') {
            steps {
                echo "1234"
                echo "GIT_COMMIT: ${env.GIT_COMMIT}"
            }
        }

        stage('运行 pytest 测试') {
            steps {
                echo "模拟 pytest 测试执行，生成 report.xml 和 report.html"
            }
        }
    }

    post {
        success {
            script {
                step([
                    $class: "GitHubCommitStatusSetter",
                    reposSource: [$class: "ManuallyEnteredRepositorySource", url: "https://github.com/cocadgy/dingofs-automation-framwork"],
                    contextSource: [$class: "ManuallyEnteredCommitContextSource", context: "ci/jenkins/pytest"],
                    commitShaSource: [$class: "BuildDataRevisionShaSource"],
                    errorHandlers: [[$class: "ChangingBuildStatusErrorHandler", result: "UNSTABLE"]],
                    statusResultSource: [$class: "ConditionalStatusResultSource", results: [[$class: "AnyBuildResult", message: "所有 pytest 测试通过", state: "SUCCESS"]]]
                ])
            }
        }
        failure {
            script {
                step([
                    $class: "GitHubCommitStatusSetter",
                    reposSource: [$class: "ManuallyEnteredRepositorySource", url: "https://github.com/cocadgy/dingofs-automation-framwork"],
                    contextSource: [$class: "ManuallyEnteredCommitContextSource", context: "ci/jenkins/pytest"],
                    commitShaSource: [$class: "BuildDataRevisionShaSource"],
                    errorHandlers: [[$class: "ChangingBuildStatusErrorHandler", result: "UNSTABLE"]],
                    statusResultSource: [$class: "ConditionalStatusResultSource", results: [[$class: "AnyBuildResult", message: "pytest 测试失败，请检查报告", state: "FAILURE"]]]
                ])
            }
        }
        aborted {
            script {
                step([
                    $class: "GitHubCommitStatusSetter",
                    reposSource: [$class: "ManuallyEnteredRepositorySource", url: "https://github.com/cocadgy/dingofs-automation-framwork"],
                    contextSource: [$class: "ManuallyEnteredCommitContextSource", context: "ci/jenkins/pytest"],
                    commitShaSource: [$class: "BuildDataRevisionShaSource"],
                    errorHandlers: [[$class: "ChangingBuildStatusErrorHandler", result: "UNSTABLE"]],
                    statusResultSource: [$class: "ConditionalStatusResultSource", results: [[$class: "AnyBuildResult", message: "构建被取消", state: "PENDING"]]]
                ])
            }
        }
    }
}